---
title: "my_code"
author: "Sarah Østrup Jensen"
date: "2022-12-01"
output: html_document
---
# This is a header

```{r load-data, message=FALSE}
library(tidyverse)
library(kableExtra)
library(rmarkdown)

# This is a comment
# Load the data set
pop_data <- read.csv("data/gapminder_data.csv")

#create a table with data from european countries in 2007 showing the countries 
#with the largest life expectancy on top

euro_data_tbl <-
  pop_data %>% 
  filter(continent == "Europe" & year == 2007) %>% 
  select(-continent, -year) %>% 
  arrange(desc(lifeExp)) %>% 
  rename("Country" = country, "Population size" = pop, "Life Expectancy" = lifeExp,
         "GDP" = gdpPercap)





```

Here we have loaded our data set ...

```{r create table}
#the dataframe that we want to display as a table
euro_data_tbl %>% 
  kbl() %>% 
  kable_styling(bootstrap_options = c("striped", "hover"))

```

Here is an example of how to display a massive table
```{r paged-table}
paged_table(euro_data_tbl)
```



```{r fig_data}
euro_data_fig <-
  pop_data %>% 
  filter(continent == "Europe") %>% 
  mutate(year = as_factor(year))

```


```{r fig}
#euro plot
euro_plot <-
  euro_data_fig %>% 
  ggplot(mapping = aes(x = year, y = lifeExp)) +
  geom_violin() +
  stat_summary(fun = median, geom = "point")

#draw euro plot
euro_plot

```





